import { readFileSync, writeFileSync } from 'node:fs';
const config = JSON.parse(readFileSync(new URL('../public/config.json', import.meta.url), 'utf8'));
if (process.env.API_BASE_URL) config.API_BASE_URL = process.env.API_BASE_URL;
else if (process.argv.includes('--render')) config.API_BASE_URL = 'https://hutube.onrender.com/api/v1';
else if (process.argv.includes('--local') || !process.env.CI) config.API_BASE_URL = 'http://localhost:5080/api/v1';
else config.API_BASE_URL = 'https://hutube.onrender.com/api/v1';
const url = new URL(config.API_BASE_URL);
if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) throw new Error('Invalid API_BASE_URL');
config.API_BASE_URL = url.href.replace(/\/$/, '');
writeFileSync(new URL('../public/config.json', import.meta.url), JSON.stringify(config, null, 2) + '\n');
