import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { App } from './app/app';
bootstrapApplication(App, appConfig).catch(() => {
  const host = document.querySelector('app-root');
  if (!host) return;

  const screen = document.createElement('main');
  screen.className = 'startup-network-fallback';
  const card = document.createElement('section');
  card.className = 'startup-network-card';
  const mark = document.createElement('div');
  mark.className = 'startup-network-mark';
  mark.setAttribute('aria-hidden', 'true');
  mark.textContent = '⌁';
  const brand = document.createElement('p');
  brand.className = 'startup-network-brand';
  brand.textContent = 'HuTube';
  const title = document.createElement('h1');
  title.textContent = 'Không thể kết nối HuTube';
  const message = document.createElement('p');
  message.textContent = 'Kiểm tra Wi-Fi hoặc dữ liệu di động rồi thử tải lại trang.';
  const retry = document.createElement('button');
  retry.type = 'button';
  retry.className = 'startup-network-retry';
  retry.textContent = 'Tải lại trang';
  retry.addEventListener('click', () => window.location.reload());
  card.append(mark, brand, title, message, retry);
  screen.append(card);
  host.replaceChildren(screen);
});
